name: Refresh investments data and re-deploy on daily basis

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 17 * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Connect workflow to repository
        uses: actions/checkout@v2
      - name: Install all required dependencies
        run: npm ci
      - name: Build the files
        run: npm run build
      - name: Scrap and re-new the data
        run: npm run scrap
      - name: Deploy to Vercel Now
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
